ALTER TABLE "vendor_payouts" ADD CONSTRAINT "vendor_payout_amount_check" CHECK ("vendor_payouts"."amount" > 0);--> statement-breakpoint
ALTER TABLE "vendors" ADD CONSTRAINT "vendor_wallet_nonnegative_check" CHECK ("vendors"."wallet_balance" >= 0);--> statement-breakpoint
ALTER TABLE "vendors" ADD CONSTRAINT "vendor_commission_rate_check" CHECK ("vendors"."commission_rate" IS NULL OR ("vendors"."commission_rate" >= 0 AND "vendors"."commission_rate" <= 100));--> statement-breakpoint
ALTER TABLE "coupons" ADD CONSTRAINT "coupon_value_check" CHECK (("coupons"."type" = 'percent' AND "coupons"."value" > 0 AND "coupons"."value" <= 100) OR ("coupons"."type" = 'fixed' AND "coupons"."value" > 0));--> statement-breakpoint
ALTER TABLE "coupons" ADD CONSTRAINT "coupon_minimum_check" CHECK ("coupons"."min_order_amount" IS NULL OR "coupons"."min_order_amount" > 0);--> statement-breakpoint
ALTER TABLE "coupons" ADD CONSTRAINT "coupon_usage_check" CHECK ("coupons"."max_uses_per_customer" > 0 AND "coupons"."used_count" >= 0 AND ("coupons"."max_uses_total" IS NULL OR ("coupons"."max_uses_total" > 0 AND "coupons"."used_count" <= "coupons"."max_uses_total")));--> statement-breakpoint
ALTER TABLE "coupons" ADD CONSTRAINT "coupon_date_check" CHECK ("coupons"."starts_at" IS NULL OR "coupons"."ends_at" IS NULL OR "coupons"."ends_at" > "coupons"."starts_at");--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_item_money_check" CHECK ("order_items"."quantity" > 0 AND "order_items"."unit_price" >= 0 AND "order_items"."total" = "order_items"."unit_price" * "order_items"."quantity");--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_money_check" CHECK ("orders"."subtotal" >= 0 AND "orders"."shipping_fee" >= 0 AND "orders"."discount_amount" >= 0 AND "orders"."discount_amount" <= "orders"."subtotal" AND "orders"."total" = "orders"."subtotal" - "orders"."discount_amount" + "orders"."shipping_fee");--> statement-breakpoint
ALTER TABLE "vendor_earnings" ADD CONSTRAINT "vendor_earning_money_check" CHECK ("vendor_earnings"."gross_amount" >= 0 AND "vendor_earnings"."commission_amount" >= 0 AND "vendor_earnings"."commission_amount" <= "vendor_earnings"."gross_amount" AND "vendor_earnings"."net_amount" >= 0);